### ISSUE TITLE
Create Alembic migration for initial creation from empty database

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/modelmeta#11]
We currently have a migration for adding a single item to the `timescale` enum. 

Due to issues documented below, we don't have an initial migration which creates all of the present tables (in the prod database) from an empty database. We should have that.

Issues: 

- When I used Alembic to autogenerate a migration from the SQLite test database (`modelmeta/data/mddb-v2.sqlite`), it detected a lot of differences (see code snippet below), most of which were undeclared contents of the database (a table, several indexes).
- When I did the same thing with a locally hosted copy of the production database made with the script `scripts/copyproddb.py`, it detected a similar but more extensive set of differences (see code snippet below). 
  - That database isn't necessarily a _perfect_ copy of the prod database (the script is a little complex), but it has got to be pretty close. 
- I haven't done the same test with the production database because Alembic always creates its `alembic_version` table if it doesn't exist, and (a) I don't think have write permission for the prod database, and (b) I'm leery of modifying the prod database without consulting you first.

Autogenerated upgrade from current SQLite test db to current SQLAlchemy declaration:
```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    with op.batch_alter_table('climatological_times', schema=None) as batch_op:
        batch_op.drop_index('climatological_times_time_set_id_key')

    with op.batch_alter_table('data_files', schema=None) as batch_op:
        batch_op.drop_index('data_files_run_id_key')
        batch_op.drop_index('data_files_unique_id_key')

    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.drop_index('ensemble_name_version_key')

    with op.batch_alter_table('grids', schema=None) as batch_op:
        batch_op.drop_constraint('grid_srid_fkey', type_='foreignkey')
        batch_op.drop_column('srid')

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('runs_emission_id_key')
        batch_op.drop_index('runs_model_id_key')
        batch_op.drop_index('unique_run_model_emissions_constraint')

    with op.batch_alter_table('times', schema=None) as batch_op:
        batch_op.drop_index('time_set_id_key')

    with op.batch_alter_table('y_cell_bounds', schema=None) as batch_op:
        batch_op.drop_index('y_c_b_grid_id_key')

    # ### end Alembic commands ###
```

Autogenerated upgrade from current copy of production db to current SQLAlchemy declaration:
```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    with op.batch_alter_table('climatological_times', schema=None) as batch_op:
        batch_op.drop_index('climatological_times_time_set_id_key')

    with op.batch_alter_table('data_file_variables', schema=None) as batch_op:
        batch_op.drop_constraint('data_file_variables_data_file_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'data_files', ['data_file_id'], ['data_file_id'])

    with op.batch_alter_table('data_file_variables_qc_flags', schema=None) as batch_op:
        batch_op.drop_constraint('data_file_variables_qc_flags_data_file_variable_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'data_file_variables', ['data_file_variable_id'], ['data_file_variable_id'])

    with op.batch_alter_table('data_files', schema=None) as batch_op:
        batch_op.drop_index('data_files_run_id_key')
        batch_op.drop_constraint('data_files_unique_id_key', type_='unique')

    with op.batch_alter_table('ensemble_data_file_variables', schema=None) as batch_op:
        batch_op.drop_constraint('ensemble_data_file_variables_ensemble_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('ensemble_data_file_variables_data_file_variable_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ensembles', ['ensemble_id'], ['ensemble_id'])
        batch_op.create_foreign_key(None, 'data_file_variables', ['data_file_variable_id'], ['data_file_variable_id'])

    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.drop_constraint('ensemble_name_version_key', type_='unique')

    with op.batch_alter_table('grids', schema=None) as batch_op:
        batch_op.drop_constraint('grid_srid_fkey', type_='foreignkey')
        batch_op.drop_column('srid')

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('runs_emission_id_key')
        batch_op.drop_index('runs_model_id_key')
        batch_op.drop_constraint('unique_run_model_emissions_constraint', type_='unique')

    with op.batch_alter_table('times', schema=None) as batch_op:
        batch_op.drop_index('time_set_id_key')

    with op.batch_alter_table('y_cell_bounds', schema=None) as batch_op:
        batch_op.drop_index('y_c_b_grid_id_key')
        batch_op.drop_constraint('y_cell_bounds_grid_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'grids', ['grid_id'], ['grid_id'])

    # ### end Alembic commands ###
```

**Comment by rod-glover** [comment]
I particularly distrust the constraint changes in the migration for the copy of the prod database.

All this indicates that:

1. The SQLAlchemy declaration is missing some elements -- at least indexes. 
2. Either my copy of the production database is significantly different than the actual production database, or the test database is significantly different (in schema).
2. We need a test migration based on the real production database to find out what's really true here.

**Comment by jameshiebert** [comment]
OK, for the most part, the ``upgrade()`` function tells me that we're not *that* far out of sync between our declarations and the actual database. There are just a few details that we missed.

This actually gives us a really good (and really specific) indication of everything that is missing from our SQLAlchemy declarations. Maybe we should take the migration code and convert all of the "drop" commands (for indicies, columns and constratins) to declarations in our schema. And then let's just remove the ``op.drop_table('spatial_ref_sys')`` from the upgrade function, since I'm pretty sure we need that and it comes with PostGIS.

**Comment by rod-glover** [comment]
Yes, my thoughts exactly, except that we can declare `spatial_ref_sys` as well in SQLAlchemy. I think we can use reflection to avoid having to explicitly declare all of its attributes. Or something like that.

**Comment by rod-glover** [comment]
Fixed in https://github.com/pacificclimate/modelmeta/pull/15
