### ISSUE TITLE
nchelpers needs to be installed from PCIC repository

### ISSUE THREAD

**Issue by corviday** [pacificclimate/modelmeta#119]
The pipfile for this package defines the PCIC repository, which contains the nchelpers package, but when installing the package, doesn't indicate that it should use the defined repository. I think the line for nchelpers should look like:

```
nchelpers = {version = "==5.5.8", source = "pcic"}
```

though I still get error messages on install after changing that, so I may need to investigate further before submitting a patch.

**Comment by eyvorchuk** [comment]
I fixed this with 
```bash
nchelpers = {version = "==5.5.11", index = "pcic"}
```

5.5.11 is the version I just made.
