### ISSUE TITLE
No longer supports PostgreSQL

### ISSUE THREAD

**Issue by basilveerman** [pacificclimate/modelmeta#3]
[RSQlite](https://cran.r-project.org/web/packages/RSQLite/RSQLite.pdf) supports dbBegin, and the code [has been adapted](https://github.com/pacificclimate/modelmeta/blob/ed894595917c6fd32fbb9b7df48dd01edc43f242/db/index_netcdf.r#L45) to use this syntax. [RPostgreSQL](https://cran.r-project.org/web/packages/RPostgreSQL/RPostgreSQL.pdf) however, does not support this. The resulting error is:

```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbBegin’ for signature ‘"PostgreSQLConnection"’
```

Possible solution could be to wrap 'begin', 'rollback' and 'commit' functions to detect db connection signature.

**Comment by rod-glover** [comment]
Irrelevant since we have transitioned to Python for the indexer.
