### ISSUE TITLE
Update database schema documentation to reflect discrete geometry changes

### ISSUE THREAD

**Issue by corviday** [pacificclimate/modelmeta#74]
Specifically, upload @rod-glover 's spiffy new ORM diagram to replace [this one](https://github.com/pacificclimate/modelmeta/blob/master/db/schema.svg).

**Comment by corviday** [comment]
Actually, uploading the new diagram in addition to the current one would probably make more sense, since we're leaving the `pcic_meta` unchanged.

**Comment by rod-glover** [comment]
[My diagram](https://github.com/pacificclimate/modelmeta/blob/master/db/modelmeta-v2-detail.dia) is already part of modelmeta.

To address the problem of finding the version of the diagram appropriate to PCIC meta, I have added one tag, `ORM-dia-61491-add-seasonal-resolution`, that points at the diagram in its latest state prior to the migration to supporting DSG as well as gridded files. The tag's message indicates it is "Valid for PDP / pcic_meta database."

I won't add any other such tags until there is clear need for them.
